---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ai-api-secret
  namespace: default
spec:
  encryptedData:
    OPENAI_API_KEY: AgBmGyy9SL3UAl4SiLk8Y8iRilwzM8oPYMQevopgnb/rFjJn2pGAOuLn0yn5TTi+ZlkoJutuYq5phv1LeVbKGU14075gn/GWJvV89mLzfxNE+ew+497ehXUL8G61qlxEmFwmS/ao2bwEUbCbOBUOD4ARvjRSYrp9LaLvFQeUjLAU/Kk5HCIpBYAc7S49HMZ+41xIEfg4up1ztNe6RjUQoV08SjUbHJWwwKMjZSxOQBwEPE1fVfpjENyB83+KG0uMxpak2RHBK6CAGRzZvM47U8IqbgXkuDojvDQyN7bc6v4MCQ5YAUu45x9H9VSXuWYxlL4vuXRNEHwWuw/JsfK6BdFWaStHBf4uWMuDjt975T3f/SA+KkMlpb6MrIYv+85uwIwt2d6PQecAPsYr2dtT7ZjgtMEnJizk8ULf9dZNP9G5C58SozTac7AnBd9U/h7YDpmtYk6/Om7kV9I2k7i/FH4+sSsjn9gOBDbOs24x/cwvY2XmU+CZKwMM0HaIknwgUGzBZreFzpd3X09/yGxEXKd3030WXrk8Rk5TamWd5skWg55bLh02I/srMXTg3SXAc+Q7KuU8qJ1w9DbGH4aldmR3JXKdLu1i0lvrLAjbk16/MxLpUmYHHQ94W1LqvtLcf9q0uB/Sag9hspt3BofcIL2TG9yu6QCTcjL3WwvXU1Q0hDqw4rzjfW7Z5cag6UMjJR/jGxvyGy5V3Y2AN+i7i2TB0Aq4nRNafh20n4rLyVmF9FJykiZgKQH7Exc29+ZHZaRpi7GODs7SnVf15NEtG1C5BY+7suKAywOoYcBhGCoASnNMNn7qapEvntSlduknf73hY8ptdPr/xa1ca69OoY4xxPucmu6CR7omrt62F3042kIdtuPc0bRyYLNwi+wOruKwF6dI4JRG8GA8PMgP5OC6Bsm+fw==
  template:
    metadata:
      name: ai-api-secret
      namespace: default
    type: Opaque
